tools:
    sensiolabs_security_checker: true
    php_cpd: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR1
            tab_width: 4
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            excluded_paths: ['app/SymfonyRequirements.php']
    php_mess_detector: true
    php_analyzer:
        enabled: true
        config:
            use_statement_fixes:
                order_alphabetically: true
    php_loc: true
    php_pdepend: true
#   php_code_coverage:
#           test_command: phpunit -c app/
