language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - phpenv rehash
  - mysql -e 'create database www_tests_symfony;'
  - mysql -e 'create database www_tests_phpbb;'
  - cp app/config/parameters_travis.yml app/config/parameters.yml
  - php composer.phar install --dev

script:
  - bin/phpunit -c app/ --coverage-clover=coverage.coverage-clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    recipients:
      - website@phpbb.com
    on_success: change
    on_failure: change

branches:
  only:
    master
