language: php
php:
  - 5.3.2
  - 5.4.0

env:
  - DB=mysql

before_script:
  - sh -c pyrus install --force phpunit/DbUnit; fi"
  - phpenv rehash
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - phpunit --configuration phpunit.xml

notifications:
  email:
    recipients:
      - unknownbliss@phpbb.com
    on_success: always
    on_failure: always

branches:
  only:
    symfony
