language: php
php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql

before_script:
  - sh -c pyrus install --force phpunit/DbUnit; fi
  - phpenv rehash
  - php composer.phar install

script:
  - tests.sh

notifications:
  email:
    recipients:
      - website@phpbb.com
    on_success: always
    on_failure: always

branches:
  only:
    master
