language: php
php:
  - 5.3.2

env:
  - DB=mysql

before_script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.3' ]; then pyrus install --force phpunit/DbUnit; fi"
  - phpenv rehash
  - cd code
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - cd ../

script:
  - phpunit --configuration tests/travis/$DB.travis.xml

notifications:
  email:
    recipients:
      - unknownbliss@phpbb.com
    on_success: always
    on_failure: always

  irc:
    channels:
      - "irc.freenode.org#unknownbliss"
    on_success: always
    on_failure: always

branches:
  only:
    symfony
