imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:               ~
    #translator:        { fallback: %locale% }
    secret:             %secret%
    router:
        resource:       "%kernel.root_dir%/config/routing.yml"
        strict_requirements:    %kernel.debug%
    form:               true
    csrf_protection:    true
    validation:         { enable_annotations: true }
    templating:
        assets_version:         v1
        assets_version_format:  %%s?%%s
        engines:
            - twig
    default_locale:         en
    trust_proxy_headers:    false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:                ~

# Twig Configuration
twig:
    debug:              %kernel.debug%
    strict_variables:   %kernel.debug%
    globals:
        facebook:       
        twitter:        
        plus_one:       

# Doctrine Configuration
doctrine:
    dbal:
        driver:     %database_driver%
        host:       %database_host%
        port:       %database_port%
        dbname:     %database_name%
        user:       %database_user%
        password:   %database_password%
        charset:    UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
