parameters:

    # When I refer to a sandbox install I refer to our sandbox and sites
    # that are on a proper remote server in a domain root (e.g. David's Site).
    # Local sites are sites on your computer/local network that probably don't have things

    # Shouldn't need to touch this
    test_database_driver:        pdo_mysql
    phpbb_test_database_driver:  pdo_mysql
    test_database_host:          localhost
    phpbb_test_database_host:    localhost
    test_database_port:          ~
    phpbb_test_database_port:    ~

    # Its not rocket science, the user should have access to make dbs and have full access to it (we create it later)
    # This is the DB for Symfony
    test_database_name:      www_tests_symfony
    test_database_user:      bamboo_test_user
    test_database_password:  hlgiHu7hFD

    # phpBB test_database
    phpbb_test_database_name:        www_tests_phpbb
    phpbb_test_database_user:        bamboo_test_user
    phpbb_test_database_password:    hlgiHu7hFD

    # Databases for testing
    test_database_driver:            pdo_mysql
    phpbb_test_database_driver:      pdo_mysql
    test_database_host:              localhost
    phpbb_test_database_host:        localhost
    test_database_port:              ~
    phpbb_test_database_port:        ~
    test_database_name:              www_tests_symfony
    test_database_user:              bamboo_test_user
    test_database_password:          hlgiHu7hFD
    phpbb_test_database_name:        www_tests_phpbb
    phpbb_test_database_user:        bamboo_test_user
    phpbb_test_database_password:    hlgiHu7hFD

    # Mailer Settings, shouldn't need to touch these unless its a live/sandbox install.
    mailer_transport:   smtp
    mailer_host:        localhost
    mailer_user:        ~
    mailer_password:    ~

    locale:             en
    secret:             ThisTokenIsNotSoSecretChangeIt

    # Location should be local, sandbox or live
    location:           local

    # Location of java on this computer/server
    java_location:      /usr/bin/java
