phpBBWebsite_About_home:
    path:  /
    defaults: { _controller: phpBBWebsiteInterfaceBundle:About:home }

phpBBWebsite_About_history:
    path:  /history/
    defaults: { _controller: phpBBWebsiteInterfaceBundle:About:history }

phpBBWebsite_About_advertise:
    path:  /advertise/
    defaults: { _controller: phpBBWebsiteInterfaceBundle:About:advertise }

phpBBWebsite_About_contact:
    path:  /contact/
    defaults: { _controller: phpBBWebsiteInterfaceBundle:About:contact }

phpBBWebsite_About_features:
    path:  /features/
    defaults: { _controller: phpBBWebsiteInterfaceBundle:About:feature }

phpBBWebsite_About_getInvolved:
    path:  /get-involved/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /get-involved/
        permanent: true

phpBBWebsite_About_features_compare:
    path:  /features/compare.php
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /about/features/
        permanent: true

phpBBWebsite_About_contact_redirect:
    path:  /contact_us.php
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /about/contact/
        permanent: true
