phpBBWebsite_About_home:
    path:  /
    defaults: { _controller: phpBBWebsiteInterfaceBundle:About:home }

phpBBWebsite_About_history:
    path:  /history/
    defaults: { _controller: phpBBWebsiteInterfaceBundle:About:history }

phpBBWebsite_About_advertise:
    path:  /advertise/
    defaults: { _controller: phpBBWebsiteInterfaceBundle:About:advertise }

phpBBWebsite_About_getInvolved:
    path:  /get-involved/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /get-involved/
        permanent: true
