phpBBWebsite_Extensions_home:
    path:  /
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Extensions:home }
    methods:  [GET]

phpBBWebsite_Extensions_rules_and_guidelines:
    path:  /rules-and-guidelines/
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Extensions:rules }
    methods:  [GET]

phpBBWebsite_Extensions_recognised_developer:
    path:  /recognised-developer/
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Extensions:recognisedDeveloper }
    methods:  [GET]

phpBBWebsite_Extensions_official_extensions:
    path:  /official-extensions/
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Extensions:officialExtensions }
    methods:  [GET]

phpBBWebsite_Extensions_official_extensions_team:
    path:  /official-extensions/team/
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Extensions:officialExtensionsTeam }
    methods:  [GET]

phpBBWebsite_Extensions_installing:
    path:  /installing/
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Extensions:installing }
    methods:  [GET]

phpBBWebsite_Extensions_team_overview:
    path:  /team-overview/
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Extensions:teamOverview }
    methods:  [GET]