phpBBWebsite_Mods_home:
    path:  /
    defaults:
        _controller:  PhpbbWebsiteInterfaceBundle:Global:template
        template: PhpbbWebsiteInterfaceBundle:Mods:home.html.twig
    methods:  [GET]
