phpBBWebsite_Support_home:
    path:  /
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Support:home }
    methods:  [GET]

phpBBWebsite_Support_irc:
    path:  /irc/
    defaults: { _controller: PhpbbWebsiteInterfaceBundle:Support:irc }
    methods:  [GET]
