phpBBWebsiteInterfaceBundle_homepage:
    path:  /
    defaults: { _controller: phpBBWebsiteInterfaceBundle:Global:home }

phpBBWebsite_Mods:
    resource: "@phpBBWebsiteInterfaceBundle/Resources/config/routing/mods.yml"
    prefix:   /mods

phpBBWebsite_Development:
    resource: "@phpBBWebsiteInterfaceBundle/Resources/config/routing/development.yml"
    prefix:   /development
