phpBBWebsite_homepage:
    path:  /
    defaults: { _controller: phpBBWebsiteInterfaceBundle:Global:home }

phpBBWebsite_mods:
    resource: "@phpBBWebsiteInterfaceBundle/Resources/config/routing/mods.yml"
    prefix:   /mods
