parameters:
#    php_bb_website_interface.example.class: phpBB\WebsiteInterfaceBundle\Example

services:
#    php_bb_website_interface.example:
#        class: %php_bb_website_interface.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    phpbb.twig.globalvars:
        class: phpBB\WebsiteInterfaceBundle\Twig\GlobalsExtension
        tags:
            - { name: twig.extension }
