phpBBUpdateGitRepoBundle:
    resource: "@phpBBUpdateGitRepoBundle/Resources/config/routing.yml"
    prefix:   /

phpBBAdminPanelBundle:
    resource: "@phpBBAdminPanelBundle/Resources/config/routing.yml"
    prefix:   /

phpBBphpBBSessionsAuthBundle:
    resource: "@phpBBphpBBSessionsAuthBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
